### ISSUE TITLE
Devaire64COM.dll 참조 문제에 관하여

### ISSUE THREAD

**Issue by winterlood** [22hours/Typress#5]
현재 
---

VS Studio 버전이 상이할 경우, 

컴파일러 버전이 상이하여, 라이브러리가 정상적으로 참조 되지 않는다 생각하여,

현재 설치되어있는 VS 모두 삭제,

VS 2019 설치 완료,

결론 : 동일한 문제 발생

**Comment by jongwuner** [comment]
슈ㅡㅡ발 이를 어쩌지

**Comment by jongwuner** [comment]
22Hours's Printer Spooler API 제작 중

**Comment by jongwuner** [comment]
@winterlood 
해결책 써주고 Close 해주세용~

**Comment by winterlood** [comment]
먼저 확인이 늦은점 너른 양해 부탁드립니다.
> 앞으론 빨리 빨리 하도록 할게요 ㅠ..

문제가 되었었던 점
---
- 1. VS compiler 버전 상호 호환성 때문에 참조가 안되었던것이 제일 큰 문제점이었던듯.
- 2. Deviare Engine 자체가, FAN 프린터 전용 컴퓨터에서는, 컴파일이 불가했던 문제점도 존재했음
- 3. Regsvr 명령을 통해, 레지스트리 자체를 64bit용으로 참조시켰어야 했음

해결한 점
---
- 1. VS 2019 버전으로 업그레이드 후 다시 컴파일 하여 dll 생성함
- 2. Deviare Engine 자체 코드 수정 (헤더파일 등등... 너무많아서 상세하게 기술하지 못했음)
